In [ ]:
1. What does Pandas stand for?
   The name Pandas stands for is "Panel Data".

2. What are the 2 collections used in Pandas?
   Two collections used in Pandas are dataframes and series.

3. Name 4 things Pandas can do for us.
   Four things Pandas can do for us are dta clensing, data normalization, data visualization, 
   and data inspection.

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
   The keyword that should be used is 'inplace' An example of this would be the following :
 
   df.sort_values(by = ['ColumnName', inplace=True])

5. What is a CSV.
   A CSV stands for Comma Separated Value. This can be used to store tabular data such as 
   spreadsheets ot databases.

6. When cleaning data what values do we not like in our data?
   Values we do not want in our data include missing values, duplicate values, and incorrect values.


In [5]:
# 7 

import numpy as np

# 12 element array.
array = np.arange(12)

# Reshape change array shape  (2,3,2)
reshaped_array = array.reshape(2, 3, 2)


print(reshaped_array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [7]:
# 8 . linespace

import numpy as np

# Create  array with 6 linearly spaced values between 0 and 20
array = np.linspace(0, 20, 6)


print(array)




[ 0.  4.  8. 12. 16. 20.]


In [9]:
# 9 Deep Copy

import numpy as np

# Create an array with 6 linearly spaced values between 0 and 20
array = np.linspace(0, 20, 6)


deep_copy = np.copy(array)


print(array)

print(deep_copy)





[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


In [8]:
# 10.

# Import the NumPy library
import numpy as np

# Define 1-D arrays
array1 = np.array([0.71, 0.1, 0.24, 0.3])
array2 = np.array([0.8, 0.59, 1.0, 1.11])

# Increase dimension of array1 to 2-D and broadcast the multiplication
result = array1[:, np.newaxis] * array2


print(result)



[[0.568  0.4189 0.71   0.7881]
 [0.08   0.059  0.1    0.111 ]
 [0.192  0.1416 0.24   0.2664]
 [0.24   0.177  0.3    0.333 ]]


In [17]:
# 11 

import numpy as np

# Define 2-D arrays
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

# Concatenate three arrays
newArray = np.concatenate((array1, array2, array3), axis=0)

print(newArray)



[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [18]:
# 12


import numpy as np

# Define 2-D arrays
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

# Concatenate three arrays
newArray = np.concatenate((array1, array2, array3), axis=0)

# Sort newArray row-wise
sortedArray = np.sort(newArray, axis=1)

# Print the sorted array
print(sortedArray)



[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [22]:
# 13

import numpy as np

# Define  2-D arrays
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

# Concatenate three arrays
newArray = np.concatenate((array1, array2, array3), axis=0)

# Sort newArray row-wise
sortedArray = np.sort(newArray, axis=1)

# Reshape sortedArray to reshapedArray
reshapedArray = sortedArray.reshape(4,3)


print(reshapedArray)



ValueError: cannot reshape array of size 12 into shape (2,3)

In [23]:
# 14


import numpy as np

# Define three 2-D arrays
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

# Concatenate three arrays
newArray = np.concatenate((array1, array2, array3), axis=0)

# Sort newArray row-wise
sortedArray = np.sort(newArray, axis=1)

# Reshape sortedArray into a new array called reshapedArray with shape (4, 3)
reshapedArray = sortedArray.reshape(4, 3)

# Unpack the arrays in reshapedArray into four variables
arrayA, arrayB, arrayC, arrayD = reshapedArray


print("Array A:", arrayA)
print("Array B:", arrayB)
print("Array C:", arrayC)
print("Array D:", arrayD)





Array A: [16 25  2]
Array B: [11  4 13]
Array C: [ 7 81  5]
Array D: [ 6 11 12]


In [24]:
# 15

import numpy as np

# Define three 1-D arrays
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Concatenate three arrays into one
comboArray = np.concatenate((one, two, three))

# Sort combined array
comboArray = np.sort(comboArray)


print(comboArray)




[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [25]:
# 16

# Import the NumPy library
import numpy as np

# Define three 1-D arrays
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Concatenate three arrays into one
comboArray = np.concatenate((one, two, three))

# Sort combined array
comboArray = np.sort(comboArray)


sec1 = comboArray[1]
print("Section 1:", sec1)

sec2 = comboArray[2:]
print("Section 2:", sec2)

sec3 = comboArray[3:14]
print("Section 3:", sec3)

sec4 = comboArray[-6:]
print("Section 4:", sec4)

sec5 = comboArray[:-15]
print("Section 5:", sec5)

sec6 = comboArray[19::2]
print("Section 6:", sec6)

sec7 = comboArray[::-5]
print("Section 7:", sec7)





Section 1: 1
Section 2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
Section 3: [ 3  4  5  6  7 10 11 12 13 14 15]
Section 4: [22 23 24 25 26 27]
Section 5: [ 0  1  2  3  4  5  6  7 10]
Section 6: [23 25 27]
Section 7: [27 22 15 10  3]


In [26]:
# 17


import numpy as np

# Define two arrays
array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                   [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                   [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array2 = np.array([[17.0, 70.0, 10.7]])

# Perform addition operation
addition_result = array1 + array2
print("Addition Result:\n", addition_result)

# Perform  division operation
division_result = array1 / array2
print("\nDivision Result:\n", division_result)

Addition Result:
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

Division Result:
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]


In [ ]:
# 18
# Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7. 
# Are we talking about point #7 in the arrays or number 17???? Am making the assumption that we are talking about number  17.


import numpy as np

# Define 2 arays
array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                   [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                   [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array2 = np.array([[17.0, 70.0, 10.7]])

# NumPy's subtract function  subtract array2 from array1
subtraction_result = np.subtract(array1, array2)

print(subtraction_result)





In [27]:
# 19

# Again I'm just goiung to make the assumption we are talking about number 17 and not point 7.
# 19. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.



# Define the array
array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                   [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                   [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

# Modulus
modulus = np.mod(array1, 3)

# Divisible 
divisible_by_3 = np.where(modulus == 0)

print("Elements in the array divisible by 3:", array1[divisible_by_3])

Elements in the array divisible by 3: [ 0.  0. 30. 24. 15.]


In [28]:
# 20 

import numpy as np

# Define array
array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                   [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                   [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]]) 

# Mod function  modulus each element divided by 3
modulus = np.mod(array1, 3)


divisible_by_3 = np.where(modulus == 0)


print("Elements in the array divisible by 3:", array1[divisible_by_3])

Elements in the array divisible by 3: [ 0.  0. 30. 24. 15.]


In [29]:
# 21

import pandas as pd


data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

# Create DataFrame
studentData = pd.DataFrame(data)

print(studentData)




      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [30]:
# 22

# Define the desserts
desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

# Add the new column to the DataFrame
studentData['Desserts'] = desserts

# Print the updated DataFrame
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [54]:
# 23

# Sort  DataFrame
studentData_sorted = studentData.sort_values(by=['Name', 'address'])


print(studentData_sorted)



      Name  Height Qualification  address  Age        Pets           sport   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [55]:
# 24 
# Save the DataFrame as a .CSV file
studentData.to_csv('studentData.csv', index=False)


In [60]:
# 25(A)

import pandas as pd

Data = pd.DataFrame({
    'Vegetable': ['Carrot', 'Broccoli', 'Spinach', 'Potato', 'Tomato'],
    'Color': ['Orange', 'Green', 'Green', 'Brown', 'Red']
    
})

print(Data)

Data.to_csv('vegData.csv', index=False)



  Vegetable   Color
0    Carrot  Orange
1  Broccoli   Green
2   Spinach   Green
3    Potato   Brown
4    Tomato     Red


In [61]:
# 25(B)


vegData = pd.read_csv('vegData.csv')


vegData['Calories (kcal)'] = [41, 55, 23, 130, 18]


vegData.to_csv('vegData_modified.csv', index=False)
